llm:
  provider: google
  config:
    model: gemini-1.5-flash
    max_tokens: 2500
    temperature: 1.0
    top_p: 0.95
    stream: false

embedder:
   provider: huggingface
   config:
       model: sentence-transformers/all-mpnet-base-v2



